### PR TITLE
MVP Completed

### PR DESCRIPTION
**Pull request by redirwin**

### CODE REVIEW

**Comment by redirwin** [comment]
Anthony, I'm still working on this but will have to continue tomorrow. Currently the add and display task functionality is working. I still need to complete the toggle tasks functionality to hit MVP, but I hope to finish that up in the morning before class.

**Comment by redirwin** [comment]
Got MVP done. I still want to add styling and a delete capability, but I'll work on those as I have time.

**Comment by adventurini** [comment]
Did a really great job here. This is a massive project. Let's get this README file rewritten, a few styles on it, and get it portfolio ready!

**Comment by adventurini** [comment]
Also Netlify!!

**Pull request merged**
